<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\fdom\\fdomdocument' => '/src/fDOMDocument.php',
                'theseer\\fdom\\fdomdocumentfragment' => '/src/fDOMDocumentFragment.php',
                'theseer\\fdom\\fdomelement' => '/src/fDOMElement.php',
                'theseer\\fdom\\fdomexception' => '/src/fDOMException.php',
                'theseer\\fdom\\fdomnode' => '/src/fDOMNode.php',
                'theseer\\fdom\\fdomxpath' => '/src/fDOMXPath.php',
                'theseer\\fdom\\xpathquery' => '/src/XPathQuery.php',
                'theseer\\fdom\\xpathqueryexception' => '/src/XPathQueryException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd